title: Andrew Feitosa # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engenheiro de Computação, Desenvolvedor Fullstack 
  <br><br>
  Olá! Sou graduado em engenharia de computação e trabalho com software a mais de 10 anos. Nos últimos 4 anos
  tenho trabalhado principalmente com React, React Native e frameworks de NodeJS.
  <br><br>
  <a href="https://www.linkedin.com/in/andrew-feitosa-9ba14043/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
