title: Andrew Feitosa # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Engenheiro de Computação, Desenvolvedor Fullstack 
  <br><br>
  Olá! Trabalho como desenvolvedor de software a mais de 10 anos. Tenho experiência com design e UX/UI. Nos últimos 4 anos
  tenho trabalhado principalmente com React, React Native e frameworks de NodeJS.
  <br><br>
  <a href="https://www.linkedin.com/in/andrew-feitosa-9ba14043/">Perfil do LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
